### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by glacroix** [irontec/ivozprovider#1007]
Hello,
I was using a former version of Artemis and reinstalled a fresh install from the ISO.
I have seen that some new elements have appeared but I don't manage to use the API I used to. 

One I auth, I have in the logs :
JWTUserToken(user=\"admin\", authenticated=true, roles=\"ROLE_SUPER_ADMIN\"))","authenticator":"Ivoz\\Provider\\Infrastructure\\Api\\Jwt\\AdminTokenAuthenticator"} []

But When I try to run any API with the token generated, I see : 
onError[801]: app.ERROR: Access Denied. [] []

And
request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php line 118 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php:118, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /opt/irontec/ivozprovider/library/vendor/api-platform/core/src/Security/EventListener/DenyAccessListener.php:79)"} []

Would anyone would have an idea where to dig ?

Thanks and regards,
Guillaume

**Comment by Kaian** [comment]
Hi @glacroix

API login was divided in 3 levels in order to implement different portals fot each level in a future. These portals will be designed for platform, brand and company administrators.

Right now, in order to use a given API level, you must provide administrator credentials for that level:

- A global admin for platform API endpoints 
- A brand admin for brand API endpoints 
- A company admin for client API endpoints 

Each API also has and exchange endpoint that can be used to impersonate a lower level administrator: You can convert a global admin token into a brand admin token in Brand API, and a Brand API token into a Company admin token in Client API. 

Also, since last release, API url must use a domain present in WebURLs section of the brand.

API is still on heavy development, so things may change in a future until we mark release stable. 

Thanks a lot for your testing and feedback!

**Comment by glacroix** [comment]
Thanks for your quick feedback @Kaian ! I keep digging...

I have set an admin (login, password and URL) for a brand. 

I can smoothly use many APIs (POST/brand/companies or POST/brand/carrier_servers for example) - mostly the APIs that used to be only for brands.

But I do not manage to use, for example features_rel_companies. It used to be a client API, but now, as far as I see, it is both in client and brand.

When I use it on client (POST/client/features_rel_companies), I have the error message :
 app.ERROR: Access Denied. [] []

When I use it on brand, (POST/brand/features_rel_companies), I have the error message :
app.ERROR: Variable "brand" is not valid around position 2 for expression `(brand == 2)`. [] []

Any clue ?
Thanks a lot !

**Comment by glacroix** [comment]
And the bog question : is there a way to define a super user to be able to consume any type of API ? According to your answer, it is the case (global admin), but could not manage to do it, so maybe I am wrong...

**Comment by mmadariaga** [comment]
Hi @glacroix,

>  is there a way to define a super user to be able to consume any type of API ? 

No, because of security checks you'll need an active brand admin for each brand in order to manage it. The same goes for client API. Anyway, you can get a brand/client admin token using a higher order token: Platform admin token to get a brand admin token and a brand token to get a client token. Just use Auth > /token/exchange endpoint with your token and target admin user name. 

To sum up, you need to register admins for every brand/client you want to manage and request their token using your platform token (or login using their user/pass if you prefer).

> When I use it on client (POST/client/features_rel_companies), I have the error message :
app.ERROR: Access Denied. [] []

That's probably because the companyId you're traying to set does not match the one on your token.
[Here]( is) you've client security rule for FeaturesRelCompany. Is that correct? The same would apply to brand API.

> But I do not manage to use, for example features_rel_companies. It used to be a client API, but now, as far as I see, it is both in client and brand.

/features_rel_companies will be read only endpoint on client API and writable on brand API on v2.11, there is a huge review going on [here](https://github.com/irontec/ivozprovider/pull/1001) 

Hope it helps

**Comment by glacroix** [comment]
Hi @Kaian ,

Thank you so much for the explanation. It makes sense now.

So I think there might be a bug in the code of brand/features_rel_companies. I can't POST anything on it using a brand token for a company belonging to this bran and when I just a GET using the Web client (who works for other APIs), I have the message : 
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "Internal Server Error"
}

Here is the problem : 
Jun  5 10:55:52 default onError[725]: app.ERROR: [Semantical Error] line 0, col 464 near 'brand = :brand': Error: Class Ivoz\Provider\Domain\Model\FeaturesRelCompany\FeaturesRelCompany has no field or association named brand [] []

Jun  5 10:55:52 default onError[725]: request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 464 near 'brand = :brand': Error: Class Ivoz\Provider\Domain\Model\FeaturesRelCompany\FeaturesRelCompany has no field or association named brand" at /opt/irontec/ivozprovider/library/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 464 near 'brand = :brand': Error: Class Ivoz\\Provider\\Domain\\Model\\FeaturesRelCompany\\FeaturesRelCompany has no field or association named brand at /opt/irontec/ivozprovider/library/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT o, partial company_a1.{type,name,domainUsers,nif,distributeMethod,maxCalls,postalAddress,postalCode,town,province,countryName,ipfilter,onDemandRecord,onDemandRecordCode,externallyextraopts,recordingsLimitMB,recordingsLimitEmail,billingMethod,balance,showInvoices,id}, partial feature_a2.{iden,id,name.en,name.es} FROM Ivoz\\Provider\\Domain\\Model\\FeaturesRelCompany\\FeaturesRelCompany o INNER JOIN o.company company_a1 INNER JOIN o.feature feature_a2 WHERE o.brand = :brand ORDER BY o.id ASC at /opt/irontec/ivozprovider/library/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []

**Comment by mmadariaga** [comment]
That was already fixed here https://github.com/irontec/ivozprovider/pull/993/commits/e7bca02f21705796863242a92891f80f43c9928f . You can either patch it yourself or wait for 2.11

Let us know if you have any further issues
