### ISSUE TITLE
Call from retail to pbx and residential fails

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#1020]
I have checked that:
PBX to Retail DDI is OK
Residential to Retail DDI is ok

but

Retail to Residential fails
Retail to PBX fails

 > [b1][9d0a4f09] [Retails.php:93           ] AGI Error ("PJSIP/b1c17rt1_vingas-00000227", "Non-T.38 call without Diversion header from RetailAccount#1 to number +34938750642│··························································································
, drop call")           

I this the desired behavior?

Docs at Client_configuration>retail_accounts says:
https://github.com/irontec/ivozprovider/blob/bleeding/doc/sphinx/administration_portal/client/retail/retail_accounts.rst#what-kind-of-calls-can-be-routed-through-a-retail-account
`
Contrary to Friends, Retail Accounts have some simplifications and limitations:

        Retail Accounts only route their assigned DDIs
        Retail Accounts only place externals calls to Carriers
        Retail Accounts only receive external calls from DDI Providers
`

After this issue I can improve the docs? Its a bit difficult to understand what is a external/internal call...in this case( I think )

Best invites ;)

Best regard

**Comment by Kaian** [comment]
Hi @gil-obradors 

I think this was fixed in a9ed8ec93b050bb74287c9b06e786ecc119f3e32

According to the commit message this problem still exists on standalone installations

**Comment by gil-obradors** [comment]
Hi!  
My test installation is  two-IP alone. ( one for trunks, one for users).
I have the configuration as a9ed8ec 

I have commented this lines from Retails agi sources:
```
 if (!$isFax && !$isCallForward) {
            $this->agi->error(
                "Non-T.38 call without Diversion header from <cyan>%s</cyan> to number %s, drop call",
                $retailAccount,
                $exten
            );
            $this->agi->hangup();
            return;
        }
```
And works fine
Only problem is registered twice at CDR as inbound and twice as outbound calls :)

I will keep the original files, only testing...


Best sips

**Comment by Kaian** [comment]
Hi @gil-obradors 

We were unable to reproduce this problem in our development environments. According to the agi lines you have pasted, the problem matches what a9ed8ec tried to fix, which required an asterisk restart.

The actual problem is that asterisk is detecting the bounced call (a call that is outgoing for a client and incoming for another) as a diverted call from retail. After applying the changes in asterisk configuration mentioned in a9ed8ec and restarting, the incoming call should be handled in trunks context and the code you mention should not even execute. 

Our development environments are based on `bleeding` branch, so there is a possibility that other commit may have fix the problem, but that is unlikely because most of the release changes are not related with the application server.

Regards

**Comment by gil-obradors** [comment]
Ok, thank you for your time!


Best sips

**Comment by Kaian** [comment]
Have you been able to reproduce this on 2.11?

The fix requires proxies restart.

**Comment by gil-obradors** [comment]
Not yet, I will try and inform you.
Maybe I have not explained well.
I'm in standalone test with different IP for users and for providers.
Actually this config
```[global]
type=global
user_agent=Irontec IvozProvider v2.10
endpoint_identifier_order=contact,ip,username,anonymous
```
I will test the change with 2.11 and report!  I'd like to test retail to retail too

**Comment by Kaian** [comment]
Thanks!, also restart asterisk after upgrading!

**Comment by gil-obradors** [comment]
I confirm with a two-ip standalone installation, this fix solves the original problem!

Thanks
