### ISSUE TITLE
Brazilian Language Support

### ISSUE THREAD

**Issue by adelphini** [irontec/ivozprovider#1040]
Hello people! I would very much like to contribute to the project by translating the same into the Brazilian language.

Thankful!

**Comment by gil-obradors** [comment]
me in Catalan

**Comment by Kaian** [comment]
One by one!

We are also working on adding other languages, but the process is not just translating some files, because we prefer to add total compatibility with the language in platform which includes 

 - Adding translations to the both administration and user portal
 - Adding language to Languages table so it can be selected in all platform select boxes
 - Updating all multi-language fields with new entries for the language being added
 - Adding generic locutions for the language (voicemail, errors, and so on)

I would take all this with calm, even more now that the summer is here and releases will slow down a bit (a new language requieres database changes and can only be scheduled in minor releases, next being 2.12.0).

That said, @adelphini as I did in #567, I would recommend you to start with administration portal translations (there are a lot!) based on https://github.com/irontec/ivozprovider/blob/bleeding/web/admin/application/languages/en_US/en_US.po

You should relpace all lines starting in msgstr with the text in Brazilian.

With that and the user portal translation you sent to my email, we have the basis to add the language.

Thanks a lot!

**Comment by gil-obradors** [comment]
Ok! with 1 month i promise catalan  po

**Comment by Kaian** [comment]
Thanks but let's create another issue for Catalan and leave this one for Brazilian 0:-)

**Comment by Kaian** [comment]
Closed due to inactivity.

Feel free to reopen if you want to reactive the translation process!
