### ISSUE TITLE
Terminal status not registered 

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1053]
Hello All !

i have created an user with assign terminal but the terminal is not getting register 
i am also trying to register in zoiper (SIP phone) as well but not getting register there as well 

please advise 

![image](https://user-images.githubusercontent.com/32220165/60606503-1f4b3f80-9dd9-11e9-8486-11053b99f538.png)

thanks

**Comment by Kaian** [comment]
Sorry, but this is not a support forum.

**Comment by rccess** [comment]
we never raised the issue for support !

since we are deploying the system for future development! 

we are highlighting the points which everyone need to know for new members of the community!
solution discussion here can help a lot for other members who are interested in ivoz  

your given hints can help the every member of community ! 

i asked this issue because i was concern about SIP and PJSIP , your system used PJSIP and something missing in the default configuration file

i have the following doubt 

is SIP registration entry needed manually in pjsip.conf ? or it take directly form DDI Provider server list 

Please advise

thanks

**Comment by Kaian** [comment]
According to the issue text the problem is a terminal is not registering. That isn't a bug in the software, that's a problem you encountered and you ask for help.

A bug description will be: I have successfully register a terminal, but user portal is not displaying the contact information properly. That's will have an explanation: kamailio saves location information into tables periodically and that field will have the register information as soon as the table has the row. 

This github project is designed for technical issues and bugs, feature request or discussion on enhancements of current functionalities. Read the FAQ and you will see we don't offer any kind of support. This is Free software, you can do whatever you want to do with it, we grant you those rights, but we don't have to provide any support, so please do not insist in that kind of issues requesting help. 

You can try asking in the IRC, there any community member may help you if they want, or you can start a community forum for new users in the project. I'll myself will redirect support questions there. 

As for your doubt: you don't have to touch any sip file at all. Read the documentation carefully (we can talk in this forum about improving documentation, your help will be appreciated). Do your test. If you can't advance and you think you have hit a bug, get all the information you can and prove it. 

Regards

**Comment by rccess** [comment]
Thanks for your quick reply !

we appreciate your time and efforts 

i will surely help in the improvement of the documents,

i will try from my side the fix the issues and challenges which i am facing , hope i will get some response on IRC for some hints which help a lot to fix the concern from my side

thanks again
