### ISSUE TITLE
Is Artemis production ready now?

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#1061]
Your last 2 releases no longer have the "This release is not yet production ready" statement.  Is that intentional or just an oversight?  Can you give us some idea when you think it might be production ready?  Weeks, months, years?

**Comment by Kaian** [comment]
Hi @powerpbx 

We're no longer adding the statement because README already mentions the status of each branch. If you use testing release, expect changes in APIs and other logics. Sometimes with new features, sometimes with new bugs.

Artemis is still testing, but all main features have been completed and, as far as we have tested, are working, so we will soon decide if we make it stable and limit its updates to bugfixes and small features. The target has been fulfilled: we have included CGRateS as billing engine and we have migrated all core from Zend Framework to Symfony.

I'm not sure when we will move it to stable, but before that we have to schedule the next testing release and its target features (maybe Debian Buster, with new Asterisk and new administration portals to replace klear ones, who knows). Most probably this will happen before end of the year, we will publish an issue with all that information.

Regards!
