### ISSUE TITLE
Implementation of Amazon Polly for TTS

### ISSUE THREAD

**Issue by rccess** [irontec/ivozprovider#1066]
Hello All , 

We are implementing "**Amazon Polly**" and "**Amazon Transcribe**" for TTS and voice recognition for auto answering of IVR  

Idea's are open for suggestion

**Comment by Kaian** [comment]
We have no knowledge or experience in amazon sdk or implementing modules in asterisk with it.

More import, I don't think these services are provided by Amazon under GPL-3 or AGPL licenses so that modules can not be included in the project (although afaik the sdk is Apache Licensed). 

Anyway, ASR will be a nice addition to the vpbx so other users may be interested in this. 

Good luck!
