### ISSUE TITLE
Exporting full CDR information

### ISSUE THREAD

**Issue by rbetancor** [irontec/ivozprovider#1099]
I see that CDR are only created for answered calls, is there any way to export the full CDRs of calls that have come in or come out from an artemis installation.

Didn't find a way to know, for example how many times someone have call a destination that have not answered.

**Comment by Kaian** [comment]
Hi @rbetancor 

Ivozprovider only takes into account answered calls. Originally only external outgoing calls were considered, because they implied price, but we also added Interna calls for vPBx. In artemis, incoming external calls are also displayed (in case some day we implement price for them).

There are no plans to include non-answered calls in the CDRs.

Regards

**Comment by Kaian** [comment]
Closing this as anwered.

Please try to use issue templates in the future.

Thanks!
