### ISSUE TITLE
[Config Limits Help Request] Rest Api Modifying Models And Json-Schema

### ISSUE THREAD

**Issue by rkm7232** [irontec/ivozprovider#1178]
Hi,
I started to add configuration limits to bleeding version and defined some models for api that works perfect.

Now I have two questions:
1.I added one field to Company (named **plan**) that keeps a relation to another table having brand's configuration limits.
The field adding process is same as another fields like language and ...
The problem is company model is not updated after the change, and field not visibled (I cleared cache too!)
Is there any location except orm files that makes this invisible in apis? How api-platform knows about fields that are visibled? (I double checked the dto and entities, nothing found)

2. After this I added a context (like withFeatures) to company, but json-schema was not shown in api-platform. How should I update that?

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [X] API
    - [ ] Other

Thank you.

**Comment by mmadariaga** [comment]
Hi @rkm7232,

Yes, there are some required steps in order to add a field to API model:

**1.** Make sure the field is exposed on ivozprovider/library/Ivoz/Provider/Domain/Model/Company/CompanyDto.php getPropertyMap method for each required context:
  - CONTEXT_COLLECTION for list GET
  - CONTEXT_SIMPLE for PUT/POST
  - CONTEXT_DETAILED for id based GET). 
  - Some entities may have their own contexts (withFeatures for instance). 
You may want to show/hide the field based on user role as well:
 - ROLE_SUPER_ADMIN on platform API
 - ROLE_BRAND_ADMIN on brand API
 - ROLE_COMPANY_ADMIN on client API

In case that the field is a foreign key to another entity, that target entity must be listed on the API configuration (ivozprovider/web/rest/**/app/config/api/raw/**.yml) so that security layer doesn't remove it. For instance:

```
Ivoz\Kam\Domain\Model\TrunksUacreg\DdiProviderRegistrationStatus:
  itemOperations: []
  collectionOperations: []
```

Remember to clear caches after any change so that API models are recalculted.

Hope it helps
