### ISSUE TITLE
[Bug Report] Upload Locution in Api

### ISSUE THREAD

**Issue by rkm7232** [irontec/ivozprovider#1228]
### Description

Hi,
When I upload a file in /client/locutions the following response shown:
```
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "Syntax error"
}
```
And this is journalctl output:
```
Dec 31 14:53:46 Debian onError[125060]: app.ERROR: Syntax error [] []
Dec 31 14:53:46 Debian onError[125060]: request.CRITICAL: Uncaught PHP Exception Symfony\Component\Serializer\Exception\NotEncodableValueException: "Syntax error" at /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/Serializer/Encoder/JsonDecode.php line 86 {"exception":"[object] (Symfony\\Component\\Serializer\\Exception\\NotEncodableValueException(code: 0): Syntax error at /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/Serializer/Encoder/JsonDecode.php:86)"} []
```
The request was sent from webapi platform:
```
curl -X POST "https://client.dashboard.local/api/client/locutions" -H "accept: application/json" -H "bla, bla, bla" -H "Content-Type: multipart/form-data" -F "locution=luc1" -F "OriginalFile=@1.mp3;type=audio/mp3"
```
---

- IvozProvider version: 2.13~2.13.2

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [X] API
    - [ ] Other

### Troubleshooting
Just upload a file through rest api...

**Comment by mmadariaga** [comment]
Hi @rkm7232,

Locution field value (you've locution and OriginalFile fields on the UI) expects a json value. For instance `{"name": "myLocution"}`. That is why you're getting NotEncodableValueException.

Unfortunately, because of UI library limitations, we can't show an example json here as we do on entities without files. 

Anyway, we try to add API tests for every API endpoint and they could help you out on future doubts: https://github.com/irontec/ivozprovider/blob/bleeding/web/rest/client/features/provider/locution/postLocution.feature

**Comment by mmadariaga** [comment]
I forgot to put curl example :)

curl -X POST "https://client.provider.com/api/client/dev.php/locutions" -H "accept: application/json" -H "Authorization: Bearer $TOKEN" -H "Content-Type: multipart/form-data" -F "locution={"name": "myLocution"}" -F "OriginalFile=@01 Llevame.mp3;type=audio/mp3"
