### ISSUE TITLE
MWI not working for residential customers 

### ISSUE THREAD

**Issue by clecny** [irontec/ivozprovider#1280]
I am using 2.14   release, and I dont see NOTIFY after leaving voice mail for residential customer.  MWI works fine for  vPBX tenants but not residential tenants.

Also, I dont see any voice notification email activity on 127.0.0.1 port 25  

I  looked for logs, no error or warning noticed.

**Comment by Kaian** [comment]
Hi @clecny 

First of, sorry for the late response. We totally missed this issue. 

Please, use provided templates for reporting Bugs or Feature request, otherwise issues may be closed automatically.

I think this was fixed in 2.15.2 in #1394 
It also mention in the logs.

Feel free to reopen the issue if you find the fix is not properly working.

Thanks for reporting
