### ISSUE TITLE
setup ivozprovider 

### ISSUE THREAD

**Issue by reagan89** [irontec/ivozprovider#1388]
Good day Team,
I am new to ivozprovider, please can i get some help.
I have installed Ivozprovider with a public IP, which i can access find how ever my ITSP have configured ther Equipment in my server server room and i have been given a sip gateway to use that will take to their equipment so that i can receive and send outbound calls.

how can i configure ivozprovider to receive and send calls through their gateway and not the public IP

**Comment by gil-obradors** [comment]
Hi @reagan89 ,

This isn't a issue for the dev of the project

In order to respect the time of the developers and the project dev itself, make the query to the users lists, I will try to help you there if you provide the appropriate information.

https://github.com/irontec/ivozprovider#feedback--questions

In advance, please read  [FAQ](https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md#) and especially [this point](https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md#can-i-use-ivozprovider-without-public-ip-address)

See you there

**Comment by Kaian** [comment]
Hi @reagan89 

As @gil-obradors mentions, we don't handle environment issues or custom setups here. We leave Github for sotware bugs and feature requests.

Feel free to join the [users-group](https://groups.google.com/forum/#!forum/ivozprovider-users), maybe someone can help you there.

Regards
