### ISSUE TITLE
Bug report: Recordings Recorded File API Token Error

### ISSUE THREAD

**Issue by rkm7232** [irontec/ivozprovider#1436]
### Description
Hi, after recording some calls on my ivozprovider server, and encoding them to mp3s, when I tried to download the file trough the client rest api, I see the following log in journalctl:

```
Jun 24 00:26:14 HPBX-1 onError[51153]: request.INFO: Matched route "api_recordings_/recording_recordedfile_item". {"route":"api_recordings_/recording_recordedfile_item","route_parameters":{"_controller":"Ivoz\\Api\\Symfony\\Controller\\DownloadAction","_format":null,"_api_resource_class":"Ivoz\\Provider\\Domain\\Model\\Recording\\Recording","_api_item_operation_name":"/recording_recordedfile","_api_resource_class_attribute":"RecordedFile","_api_receive":true,"id":"1","_route":"api_recordings_/recording_recordedfile_item"},"request_uri":"https://172.25.17.54/api/client/recordings/1/recordedfile","method":"GET"} []
Jun 24 00:26:14 HPBX-1 onError[51153]: app.ERROR: A Token was not found in the TokenStorage. [] []
Jun 24 00:26:14 HPBX-1 onError[51153]: security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:51)"} []
```

---

- IvozProvider version: 2.14~2.14.1~20200207.2502~2bf5727+artemis all

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [X] API
    - [ ] Other

### Additional Information
File recording is normal, and could be downloaded from ivozprovider dashboard.

**Comment by mmadariaga** [comment]
Hi @rkm7232,

You're using API UI here, right? I seems to be a swagger UI issue, It adds html5 audio tag so that you can listen the audio on the web. The thing is that image/audio contents are requested again by the browser but it's not sending the Authorization header here. I've tried to download the audio directly from console and it's working properly:

`curl 'https://client-domain/api/client/recordings/$ID/recordedfile'  -H 'accept: application/octet-stream'   -H 'Authorization: Bearer $TOKEN' --compressed -k --output audio.mp3`

We can try to upgrade swagger UI, it might be already fixed, I consider it low prio though.

**Comment by rkm7232** [comment]
thanks, you're right...
