### ISSUE TITLE
passwords rejected characters

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#155]
The terminals password generator sometimes generates passwords that contains the # $ ! @ ^ symbols. Those passwords are then rejected by the form validation on save.

Ivozprovider v.1.3

**Comment by cruzccl** [comment]
Hi Manfer,

Which version of IvozProvider are you using? We detected this annoying issue and tried to fix it with 35e146e.

Since this commit, only _ - + * are suggested by the password generator and all of them should be allowed by the form validation.

We removed some characters as they conflicted with some provisioning template formats.

Thank you very much :)

**Comment by manfer** [comment]
v.1.3

I'm creating new Terminal. It is not an old one.

The password generator sometimes creates password with those characters. When I click the refresh button to generate a new password many times the field is filled with a password containing one of those passwords, # $ ! @ ^. And when I try to save the field becomes red and shows the corresponded error message on top of it.

**Comment by cruzccl** [comment]
Could you please inspect the element with the browser and see if the underlying JS code has this conflicting symbols?

If the browser tab was loaded some time ago, I would reload the page before inspecting it :)

**Comment by manfer** [comment]
ok, maybe a browser cache issue. I will test that an report back.

**Comment by manfer** [comment]
Ctrl-Shift-R and now the password generator generates only valid passwords.

Thanks

**Comment by cruzccl** [comment]
Glad to hear that, I close the issue then :)

Regards.
