### ISSUE TITLE
username remains

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#160]
Username has been dropped with the commit [49f2ffe869dfc42aad5a48da8b5bf67d9b532f08](https://github.com/irontec/ivozprovider/commit/49f2ffe869dfc42aad5a48da8b5bf67d9b532f08)

But if we do a search from the root of the source code after a git clone

`grep -rnw . -e 'username'`

we can see some remains of username on the code.

The ones on the ./scheme/deltas folder are legitime but looks like all the rest of lines of code -or at least some of them- are not needed anymore. Some of them must be just edited to remove username.

**Comment by Kaian** [comment]
Hi @manfer 

The mentioned commit removed the _username_ field from Users table, because it's not longer used for userweb login.

Other tables, like MainOperators, BrandOperators, CompanyAdmins still have the field _username_ because it's portal ([klear](https://github.com/irontec/klear) based) stil use it for authentication. _username_ is also used to mention the user part of the SIP uri when terminals send their REGISTER messages, so it's presence in kam_users_location still makes sense. Not all username hits are an error!

We store in the git project repo some autogenerated data that I will soon remove and ignore (like portals/application/configs/klearRaw/  or  portals/application/modules/restRaw/) because their only serve as templates and they changes don't provide any useful information.

So the we have to focus specially on references in Users yaml and files that can be still residual:

 - portals/application/configs/klear/UsersList.yaml
 - portals/application/configs/klear/model/Users.yaml
 - library/IvozProvider/Klear/Auth/User.php
 ...

I will keep these and check it whenever we have some spare time.

Thanks a lot for taking the time to report!

**Comment by Kaian** [comment]
Already done in  #382
