### ISSUE TITLE
voicemail: user-extension-voicemail triggers

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#161]
It seems that there is an error in the logic that creates/updates voicemails in ast_voicemail.

This sequence generates an error:

1. Create an extension 101.

2. Create user alice.

3. Assign extension 101 to alice.

4. Edit extension 101 and change it to 102.

Voicemail will still points to 101@company.

_Additional note:_

- If a user with voicemail disabled calls to voicemail service code, the call should be rejected (instead of asking for a user extension).

**Comment by Kaian** [comment]
There's an underlaying problem here:

 - Portals assume Voicemail == User with voicemail enabled
 - ApplicationServer assume Voicemail == Extension

While both aspects can be correct, this difference makes the portal not to update the voicemail when the extension changes (only when the user changes). 

**What is more, if you swap the extension of two users, you're also swapping their voicemails, because the directories for each user in shared storages use their extension.**

```

└── company1
    ├── 1008
    │   ├── INBOX
    │   │   ├── msg0000.txt
    │   │   └── msg0000.wav
    │   ├── Old
    │   ├── tmp
    │   └── Urgent
    ├── 1020
    │   ├── Cust4
    │   │   ├── msg0000.txt
    │   │   └── msg0000.wav
    │   ├── INBOX
    │   ├── Old
    │   ├── tmp
    │   ├── unavail.wav
    │   └── Urgent
```

**Comment by Kaian** [comment]
I can do the Additional note for 1.4 but I think we have to analyze this for the next release.

_If a user with voicemail disabled calls to voicemail service code, the call should be rejected (instead of asking for a user extension)._

**Comment by Kaian** [comment]
I move this to 1.X, we have to evaluate and discuss this.

**Comment by cruzccl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [voicemail: user-extension-voicemail triggers](https://trello.com/c/9Frgpdnl/5-voicemail-user-extension-voicemail-triggers)
