### ISSUE TITLE
 how to install on vps

### ISSUE THREAD

**Issue by Maisfone** [irontec/ivozprovider#1632]
hello, is it possible to install on a vps?

**Comment by Kaian** [comment]
Please use provided templates for bugreports or feature request when submitting issues, otherwise issues will be closed unanswered.

IvozProvided is not currently ready for some cloud enviroments like AWS where public IP is not available to be directly binded by applications. If thats not the case it may work.

You can try asking for enviroments and setups in the users group.

Regards
