### ISSUE TITLE
How to provision and create extension?

### ISSUE THREAD

**Issue by RealAgent** [irontec/ivozprovider#209]
Hi.

I have a question. How to provision and create extension in fresh Ivoz Provider? 
Can u help me?

**Comment by Kaian** [comment]
HI @RealAgent 

I assume you have installed a standalone version of IvozProvider.

After installing you can [access the web portal](https://irontec.github.io/ivozprovider/en/internal_calls/god_portal.html) to configure almost everything in the platform.

Extensions are a Company entity so you must first [emulate one brand](https://irontec.github.io/ivozprovider/en/internal_calls/god_portal.html#emulate-the-demo-brand) and then [emulate one of its companies](https://irontec.github.io/ivozprovider/en/internal_calls/brand_portal.html#emulate-demo-company)

The company menu has entries for [Extensions](https://irontec.github.io/ivozprovider/en/pbx_features/extensions.html), [Terminals](https://irontec.github.io/ivozprovider/en/pbx_features/terminals.html) and [Users](https://irontec.github.io/ivozprovider/en/pbx_features/users.html).

[Terminal provisioning](https://irontec.github.io/ivozprovider/en/provisioning/index.html) is currently supported for a couple of terminals, provided you have configured them to request provisioning data to the portal address and the _/provision/_ path (see docs).

Best regards,
Kaian

**Comment by RealAgent** [comment]
Maybe u have a Skype ID? I have lot of question about this. We are VOiP Providers basen in London. 

Best Regards!

**Comment by Kaian** [comment]
Hi @RealAgent 

Our community support is offered here via github issue. Any response can provide some light to other people trying to test the solution.

If you prefer, you can contact with our comercial team at comercial@irontec.com in order to have personalized information or dedicated time for any of your needs.

Otherwise, patience is required as we'll strive to answer any or doubts and lister to any suggestion written in this issue.

Best regards,
Kaian

**Comment by RealAgent** [comment]
how do we set up from start to finish 1. reseller 2. Company 3. users / extension as your user guide is not very westernised. We have tried ourselves however it doesn't seem very automated, as you have to do thing more than once. 

Regards 

DannyWrigss

**Comment by Kaian** [comment]
Hi @RealAgent 

As you may have guessed by the available docs, our native language is spanish. However, we tried to do our best and write all the [documentatio files](https://github.com/irontec/ivozprovider/tree/bleeding/doc/sphinx) english (and then translate them to our native language). This way, english native speakers can contribute, enhance and update easily while we make the correct translations.

The docs are not an indeep guide for sure as we are a little team, but they should cover the basic for each section (Brand, Company, Users or Terminals), otherwise they are useless and any contribution to improve this are highly appreciated.

Although we know the portal interface requires a lot of work (and it's already schedulled for the next major release that we hope to have by the end of the year), it still allows creation of all of the mentioned entities. 

Right now there is no _automated_ way to create almost anything: you must navigate a couple of sections in order to have the requires entities to use the platform. There is a generic Rest API interface but we haven't documented it because it still requires a lot of work to make it usable for provisioning and integrating other softwares (but we'll also get there).

Brands are one of the topmost entities of the platform that can provide service to clients. They are in charge of configuring routes, pricing plans, and basic client setup. You can find more info [here](https://irontec.github.io/ivozprovider/en/operation_roles/index.html#brand-andministator-role)

Right now there are a couple of different clients: VirtualPBX (aka Companies) and Retail. We're planning on adding new types, like for example Residential (see #193). Depending on their type, they can be as simple as a retail account (basically some SIP credentials with vitamins) and its DDIS, or a lot of entities and logics to route calls (Huntgroups, IVRs, Queues, and so on).

For virtual pbx companies, the main entity is the user (in fact they have their [own portal](https://irontec.github.io/ivozprovider/en/userportal/index.html). It has an extension and terminal associated that must be created previously (in their own sections). And yes, right now they must be created one by one (although the creation screen only haves a couple of fields to simplify the process a bit). You can find more information [here](https://irontec.github.io/ivozprovider/en/operation_roles/index.html#company-administator-role)

Terminals provide the basic information for a SIP capable endpoint, while Extensions works a simple numeric alias that can be dialed.

As you can see, we've taken some time to write this long note. It may not provide the information you were asking (because sadly we don't have the time for explaining all the entities from start to end), so the more precise the question, the more clear the answer will be. As mentioned before, don't hesitate to contact or commercial team if you feel the need to have an extensive course of the software!

Best regards!

**Comment by RealAgent** [comment]
Problem when I added terminal and extension - my phone still can not connect to pbx. In the bookmark TERMINALS the system shows an exclamation point - it concludes that somewhere has crept into the problem? (Status).

**Comment by cruzccl** [comment]
I @RealAgent 

The exclamation mark in Terminals section shows that the terminal has not an active registration.

There are multiple reasons why this could happen and the tools to troubleshoot this situation are documented in https://irontec.github.io/ivozprovider/en/maintenance/index.html#maintenance-and-troubleshooting.

The first step would be to ensure that a REGISTER request of the terminal is reaching IvozProvider. The easiest way would be using _sngrep_ (see https://irontec.github.io/ivozprovider/en/maintenance/sip_captures.html). Type `sngrep` in the shell and reboot your phone to force its registration:


- If you don't see a REGISTER coming from your phone, the problem is outside IvozProvider (maybe the _SIP proxy_ in the phone settings?). 
- If you see a REGISTER request:
  - If IvozProvider replies, the next step would be inspecting KamUsers logs as explained in https://irontec.github.io/ivozprovider/en/maintenance/log_viewer.html#kamailio-realtime-log-viewing. Typing `kamtail-proxyusers` and rebooting the phone may help.
  - If IvozProvider does not reply, the problem could be that KamUsers is not running or is not listening to that IP/PORT. You could run `systemctl status kamailio@users` to see if the process is UP.

I hope this helps, thank you for testing IvozProvider!

Regards,

**Comment by RealAgent** [comment]
I think - this is a problem with my KamServer. 
SSH show me error status: 

[Jul 13 15:32:03] db_mysql [km_res.c:142]: db_mysql_get_columns(): unhandled data type column (did) type id (6), use DB1_STRING as default
[Jul 13 15:36:06] db_mysql [km_res.c:142]: db_mysql_get_columns(): unhandled data type column (did) type id (6), use DB1_STRING as default
[Jul 13 15:36:20] db_mysql [km_res.c:142]: db_mysql_get_columns(): unhandled data type column (did) type id (6), use DB1_STRING as default
[Jul 13 15:37:32] db_mysql [km_res.c:142]: db_mysql_get_columns(): unhandled data type column (did) type id (6), use DB1_STRING as default
[Jul 13 15:39:26] db_mysql [km_res.c:142]: db_mysql_get_columns(): unhandled data type column (did) type id (6), use DB1_STRING as default
[Jul 13 15:44:08] db_mysql [km_res.c:142]: db_mysql_get_columns(): unhandled data type column (did) type id (6), use DB1_STRING as default
[Jul 13 15:47:08] db_mysql [km_res.c:142]: db_mysql_get_columns(): unhandled data type column (did) type id (6), use DB1_STRING as default
[Jul 13 15:47:26] db_mysql [km_res.c:142]: db_mysql_get_columns(): unhandled data type column (did) type id (6), use DB1_STRING as default

Maybe you know how can i fix it? 

Thank you for patience and help!

**Comment by RealAgent** [comment]
![sngrep](https://user-images.githubusercontent.com/30153776/28223680-42abcd7e-68c4-11e7-8877-ad50b0555bae.png)

This is screen from SSH - sngrep command.

**Comment by Kaian** [comment]
There should be 2 kamailio proxies running. The one that handles terminal registrations is called kamailio@users

Does users.ivozprovider.local resolve to 78.129.239.136?

Are you using differente IPs for users.ivozprovider.local and trunks.ivozprovider.local?

Bes regards,

**Comment by cruzccl** [comment]
Closed due to lack of feedback. Feel free to reopen.
