### ISSUE TITLE
Rest API Docs?

### ISSUE THREAD

**Issue by flantel** [irontec/ivozprovider#220]
Hi
Nice work. Is there documentation on the Rest API yet?

**Comment by Kaian** [comment]
Hi @flantel 

Thanks!

Currently the Rest API is generated automatically and has no proper filtering and control. That means that any logged main administrator could create, edit or remove any entity without control (even those read only in the portal). For that reason we discourage its usage right now.

As we understand that integrating with third-party software is highly required and demanded, we're already working on reimplementing current backend in [another branch](https://github.com/irontec/ivozprovider/commits/loose-coupling) so we create new APIs on top of it. The new created APIs will have more control of what user can see and modify and how many times can do it, but **will be incompatible with current one**.

We don't have a official release date for the new backend, so if you still need to check the current Rest API implementation, there are some examples in your installation apidocs: https://your.main.portal.com/apidocs/

Site credentials are _admin_:_changeme_ then you must fill a valid main administrator user and pass in order to fetch data.

Best regards!

**Comment by flantel** [comment]
Thanks very much
