### ISSUE TITLE
multi-site setup

### ISSUE THREAD

**Issue by syadnom** [irontec/ivozprovider#223]
I'm looking at the image of the general diagram, as well as the service block diagram which tells me that each service can be scaled out, but how about multi-datacenter deployments?

I see MySQL 5.5 is the listed db, but I don't think this can do multi-source replication, so are we stuck with circular replication (100% dealbreaker here) or can mysql 5.7 be used?  or, is there a different replication model here?  In short, what is the multi-database replication model here and can that scale beyond a single datacenter without using circular replication?

I see that redis is also being used, so what is your multi-redis server replication model?

A scenario here would be 3 datacenters, all running a full stack and all with multiple asterisk servers.

**Comment by Kaian** [comment]
Hi @syadnom 

Most of the services can scale, but not all of them. For example, we use two SIP Proxies (kamailio) for routing SIP trafic to endpoints (one for carriers and one for users). You can scale Application Servers, Media Relays, Databases, etc...

Platform require a MySQL database and we use Debian Jessie as base system so 5.5 is what we've docummented that works. But if we change a bit package dependencies (currently _mysql-server_ is pulled as [dependency](https://github.com/irontec/ivozprovider/blob/bleeding/debian/control#L68)) to be more flexible, you can change mysql server with other choices (like galera, mysql cluster, mysql 5.7, etc) and everything should work. Most of the times, we use two node MySQL master-master replication with a balanced IP, but this may not be enough for some environments.

Redis is included in the platform because our starting approach for realtime status publishing was done by kamilios and redis, but after some testing we don't think that's the proper way to do it for our setaup, so until we have the time to think, dabate and implement another way, redis-servers won't be used.

Thanks for the testing and feedback!

Best regards

**Comment by syadnom** [comment]
What didn't you like about redis for this role?  It seems a good fit.  MySQL on the other hand would be sing disk IO for these operations which I think is a bad thing.

**Comment by Kaian** [comment]
We like redis indeed, but we didn't like publishing from kamailio.
We prefer focusing in routing and accounting in kamailio and maybe using another software to publish current dialogs to redis, but realtime requires still a lot of analyze.
