### ISSUE TITLE
transcoding

### ISSUE THREAD

**Issue by syadnom** [irontec/ivozprovider#224]
I'm looking through the platform diagrams and components here and it looks like the software tools would require transcoding to be done on the application servers (ie asterisk), is this correct?  My goal here is to have opus be the primary codec for endpoints, but providers are essentially all still using g.711 so transcoding is a necessity.

since opus is so cpu needy, this implies many application servers as well. 

Is this the model? having asterisk do the transcoding?

**Comment by Kaian** [comment]
Hi @syadnom 

Yep, asterisk (the main Application Server profile software) is the one in charge of transcoding between endpoints.

Asterisk will try always to remove itself from the media path so endpoints _talk_ directly through media-relays (rtpproxy or rptengine), but that only happens if there are compatible codecs between the final endpoints, because media-relays has no transcoding capabilities.

Currently, the endpoint representing carriers only support g711a and g729 (and maybe we should enable g711u too), so if your user endpoints only support opus, then the media liberation process won't occur and asterisk will stay in the media path translating between both endpoints.

```
Carrier <--(g711a)--> MR <--(g711a)--> Asterisk <--(opus)--> MR <--(opus)--> User
```

While we initially supported multiple codecs for user's endpoints, we restricted them to only one until we could evaluate properly all possible scenarios (for example, some terminals doesn't work as expected if they send and receive asymmetric RTP).

Best regards,

**Comment by syadnom** [comment]
I'm in north america so g711u is needed.  Thanks.
