### ISSUE TITLE
Call forward for external numbers is not charging

### ISSUE THREAD

**Issue by dbbrito** [irontec/ivozprovider#2340]
### Description

The Call forward feature for external numbers is not charging the calls, the biggest problem is that the end user can configure it through the customer portal, if all customers find out that this call is being free, the damage to the brand can be great. In Brand>>CALLS>>External Calls it shows the call, but the value is blank.
Thanks

- IvozProvider version:  - Last 3.2.0

- Related sections: 
    - [ ] SIP & Telephony
    - [ ] vPBX Functionalities
    - [X] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
Problem reproduction: Client Configuration>>Residential Devices>>List of Call forward settings>>Add Call forward setting>>YES>>Unconditional>>Target>Number.
Log asterisk:  https://pastebin.freeswitch.org/view/3531a277
Log proxytrunks:  https://pastebin.freeswitch.org/view/399805b0

**Comment by Kaian** [comment]
Hi @dbbrito!

According to the proxytrunks logs there are two calls involved:

Inbound from DDI Provider to Residential device: (Call-ID: 4390090304-3900175719-1664270866@JKSBCQ21-02.mydomain.com)


> [Aug 04 19:08:59] acc [acc_cdr.c:392]: log_write_cdr(): start_time=1691186929.441; end_time=1691186939.456; duration=10.015; brandId=1; companyId=2; caller=+553438233779; callee=+551920186817; callid=4390090304-3900175719-1664270866@JKSBCQ21-02.mydomain.com; callidHash=30d772cf; xcallid=; diversion=; carrierId=; direction=inbound; bounced=; cgrid=; retailAccountId=; residentialDeviceId=1; parsed=0; userId=; friendId=; faxId=; ddiId=11; ddiProviderId=1

Outbound from Residential Device to Call Forward Destination (Call-ID: fc7038fd-0f36-44f4-9bde-76bb50c2e00f)

> [Aug 04 19:08:59] acc [acc_cdr.c:392]: log_write_cdr(): start_time=1691186928.682; end_time=1691186939.460; duration=10.778; brandId=1; companyId=2; caller=+553438233779; callee=+5534999423533; callid=fc7038fd-0f36-44f4-9bde-76bb50c2e00f; callidHash=099bdf91; xcallid=4390090304-3900175719-1664270866@JKSBCQ21-02.mydomain.com; diversion=+5510100; carrierId=2; direction=outbound; bounced=; cgrid=72a6af69dd0102cf16f287c56dcc11d9e5e1ca64; retailAccountId=; residentialDeviceId=1; parsed=0; userId=; friendId=; faxId=; ddiId=7; ddiProviderId=

There are two calls, and it should have two different rows in BillableCalls. The first one will never be tarificated, because IvozProvider does not support Inbound tarification. But the second one is actually being tarificated according to logs:

```
[Aug 04 19:08:40] [099bdf91] CGRATES-AUTH-REPLY: Max-session-time: 5304 (b1:c2:+5534999423533:*pseudoprepaid)
[Aug 04 19:08:59] [099bdf91] CGR-CALL-END: Warn CGRates that call has ended (duration: 11)
```

So these calls are not free and Retail Client balance should be decreasing. There is also a cgrid in outbound call record (cgrid=72a6af69dd0102cf16f287c56dcc11d9e5e1ca64), so you could check CGRateS info for this call in tp_cdrs.

Can you provide the result of the query:

```
SELECT * FROM BillableCalls WHERE callid IN ('4390090304-3900175719-1664270866@JKSBCQ21-02.mydomain.com', 'fc7038fd-0f36-44f4-9bde-76bb50c2e00f')
```

Regards!

**Comment by dbbrito** [comment]
Problem solved, I restarted the server and the call was charged normally.
