### ISSUE TITLE
Load balancing

### ISSUE THREAD

**Issue by damidani** [irontec/ivozprovider#2409]
Hello,
I would like to know how load balancing works? 

how to do it?

**Comment by Kaian** [comment]
Hi!

Use provided templates when opening new issues, otherwise they may be closed without response. If your issue is not a bug report or feature request, please use users group to share or request information to other users.
https://groups.google.com/g/ivozprovider-users

Also be sure to read FAQ before posting any issue. 
https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md

If your question is regarding distributed installations, check this point.
https://github.com/irontec/ivozprovider/blob/bleeding/FAQ.md#i-have-tested-standalone-how-can-i-install-a-distributed-installation

Best Regards
