### ISSUE TITLE
Userportal - Translation

### ISSUE THREAD

**Issue by Net-Spacy** [irontec/ivozprovider#242]
Is it possible to create own translation for the Web GUI? We are planning to use the solution - but we need our main language (GER) for our customers.

Can anybody tell me: can we - and how can we make a translation of the portal?

**Comment by Kaian** [comment]
Hi @Net-Spacy 

Yes, it can be done, but It will require some schema changes because some tables has multi-language fields (see #218).

The rest of strings are classic gettext translations, so adding a new language should not be hard.

- [Admin portals](https://github.com/irontec/ivozprovider/tree/bleeding/portals/application/languages)
- [User portal](https://github.com/irontec/ivozprovider/tree/bleeding/userweb/app/languages)
- [Documentation](https://github.com/irontec/ivozprovider/tree/bleeding/doc/sphinx/locale)

We could also add GER sounds to the pbx in [asterisk-sounds](https://github.com/irontec/asterisk-sounds) package.

**Comment by zhulizhong** [comment]
I can add chinese.

**Comment by cruzccl** [comment]
Added english in #506, we close this issue to focus on the active ones.

Regards,
