### ISSUE TITLE
Caller ID not found (INVITE FROM)

### ISSUE THREAD

**Issue by damidani** [irontec/ivozprovider#2558]
### Description
When receiving a call from my VoIP provider, Ivozprovider cannot understand the number called...
it puts: 1710163127241 instead of +3300000000
---

- IvozProvider version: 2.23~2.23.0~20230227

- Related sections: 
    - [X] SIP & Telephony
    - [ ] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting

11/03/2024 14:19:38.047 +01:00: 185.1XX.XXX.XX:5060 -> 89.18X.XXX.XX:7060
INVITE sip:1710163127241@89.18X.XXX.XX:7060;transport=udp SIP/2.0
Via:  SIP/2.0/UDP 185.1XX.XXX.XX:5060;branch=z9hG4bK+e9425de232b66e5dc96fad971fff19c53+sip+6+d038ff3d
From:  <sip:+33764XXXXXXX@pbx.XXXXX.com>;tag=185.1XX.XXX.XX+6+76cd6937+dc89f19a
To:  <sip:+3300000000@pbx.XXXXX.com>
CSeq:  1061482079 INVITE
Expires:  300
Content-Length:  211
Call-Info:  <sip:185.1XX.XXX.XX:5060>;method="NOTIFY;Event=telephone-event;Duration=2000"
Supported:  resource-priority,siprec, 100rel
Contact:  <sip:k8c10966d5c46d9939ddf5e80a0c9064@185.1XX.XXX.XX:5060>
Content-Type:  application/sdp
Allow-Events:  message-summary,refer,dialog,line-seize,presence,call-info,as-feature-event,calling-name,ua-profile
Call-ID: 0gQAAC8WAAACBAAALxYAAIBpvhhdcB6dxrpsgrmSLyhLrknPVegVwwBBw3egI2tG@185.1XX.XXX.XX
Organization:  MSW
Max-Forwards:  55
P-Asserted-Identity:  <sip:+33764XXXXXXX@pbx.XXXXX.com>
Accept:  application/sdp, application/dtmf-relay

### Additional Information
Here is the capture of the packet I received... Note that it works with all other pbx (Grandstream, asterisk...)

**Comment by Kaian** [comment]
Hi,

IvozProvider does a couple of transformations to called number in order to match its E.164 format with the DDIs tables. This transfomations are usually removing or adding prefixes, but not changing the whole number. 

This doesn't seem to be a bug in the transformations process, and it not likely the inbound transformation are not working for 2.23 (that version hasn't received changes since a lot).

Please provide a full zipped PCAP capture of a call with this behaviour and call logs of all the components that are relevant (kamailio@trunks, kamailio@users or/and asterisk)


Regards

**Comment by Kaian** [comment]
This was not possible to reproduce in any environment, and doesn't look like a bug in the software.

If you still have this problem, feel free to post all relevant data in users-group adding logs, pcaps and configuration of the carrier.

Best regards
