### ISSUE TITLE
Basic Queue support

### ISSUE THREAD

**Issue by cruzccl** [irontec/ivozprovider#26]
Add new inbound logic: queue.

Only queue basics are included:

- Queue weight
- Strategy (round-robin, ringall, random, least recent, etc.)
- Wrap-up time
- Max length
- Max wait time
- Periodic announces
- Agent priorities

The goal of this feature is to make possible to distribute calls using a queue logic, but **does not convert IvozProvider into a Callcenter solution**: there are no reports, no realtime queue visualization, etc.

**Comment by Kaian** [comment]
The basic implementation for this is done at 76e6dfa16ae8e43f86ba1574d16b5236a7240006 and it's available on bleeding release.

Beware that bleeding also have kamailio-presence feature so in order to use Queues in a distributed installation of IvozProvider, each new company must statically be assigned to an application server (breaking all the horizontal scaling model).

You've been warned!
