### ISSUE TITLE
Process for moving from single server to 'production'?

### ISSUE THREAD

**Issue by syadnom** [irontec/ivozprovider#269]
I don't see in the docs how to go from a single server to a cluster.  I see the installers for separate roles, but nothing specific about "install proxy roll, the add to ivoz portal, etc etc"

I want to setup a test bed AND move through a single server to multiple server system as part of my evaluation.

Thanks.

**Comment by cruzccl** [comment]
Hi @syadnom ,

We opened #271 in order to document better the installation of distributed environments that will cover:

- One machine per profile installations.

- AS and media-relay horizontal scaling.

Read #271 for further information.

Standalone installations are only meant for having a look at the solution and make some tests. Unfortunatly, there is not any automatic process that migrates from an standalone installation to a distributed one.

Regards,
