### ISSUE TITLE
problem of provisioning a Yealink terminal 

### ISSUE THREAD

**Issue by Mahjoub-Sami** [irontec/ivozprovider#2800]
### Description

the problem of provisioning a Yealink terminal every day I cannot put into service for version 4.2 these error messages is that normal because the development is not finished or lack of knowledge to make it work

Oct 29 07:01:40 web php.onError[1245]: request.INFO: Matched route "provisionGeneric". {"route":"provisionGeneric","route_parameters":{"_route":"provisionGeneric","_controller":"Controller\\ProvisionController::indexAction","params":"XXXXXXXXXX.cfg"},"request_uri":"http://192.168.10.220/provision/XXXXXXXXXX.cfg","method":"GET"} []
Oct 29 07:01:40 web php.onError[1245]: php.INFO: User Deprecated: Since symfony/framework-bundle 5.3: The "session.storage.factory.service" service is deprecated, use "session.storage.factory.native", "session.storage.factory.php_bridge" or "session.storage.factory.mock_file" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/framework-bundle 5.3: The \"session.storage.factory.service\" service is deprecated, use \"session.storage.factory.native\", \"session.storage.factory.php_bridge\" or \"session.storage.factory.mock_file\" instead. at /opt/irontec/ivozprovider/microservices/provision/var/cache/prod/ContainerUS4EjDP/getSession_Storage_Factory_ServiceService.php:22)"} []
Oct 29 07:01:40 web php.onError[1245]: php.INFO: User Deprecated: Since symfony/framework-bundle 5.3: The "session.storage.native" service is deprecated, use "session.storage.factory.native" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/framework-bundle 5.3: The \"session.storage.native\" service is deprecated, use \"session.storage.factory.native\" instead. at /opt/irontec/ivozprovider/microservices/provision/var/cache/prod/ContainerUS4EjDP/getSession_Storage_NativeService.php:22)"} []
Oct 29 07:01:40 web php.onError[1245]: php.INFO: User Deprecated: Since symfony/framework-bundle 5.3: The "session.storage.metadata_bag" service is deprecated, create your own "session.storage.factory" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/framework-bundle 5.3: The \"session.storage.metadata_bag\" service is deprecated, create your own \"session.storage.factory\" instead. at /opt/irontec/ivozprovider/microservices/provision/var/cache/prod/ContainerUS4EjDP/getSession_Storage_MetadataBagService.php:22)"} []

Oct 29 07:01:40 web php.onError[1245]: php.INFO: Deprecated: Ivoz\Provider\Domain\Model\User\User implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) {"exception":"[object] (ErrorException(code: 0): Deprecated: Ivoz\\Provider\\Domain\\Model\\User\\User implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) at /opt/irontec/ivozprovider/library/Ivoz/Provider/Domain/Model/User/User.php:18)"} []
Oct 29 07:01:40 web php.onError[1245]: app.ERROR: Terminal model not found [] []

Thanks
---

- IvozProvider version: 4.2 

- Related sections: 
    - [ ] SIP & Telephony
    - [X] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

**Comment by Kaian** [comment]
Hi, 

The last line in your log:

```
Oct 29 07:01:40 web php.onError[1245]: app.ERROR: Terminal model not found [] []
```

Is caused because there is not terminal model configured with a generic URL that matches XXXXXXXXX.cfg
Yealink should make a generic request for initial provisioning like:

- http://192.168.10.220/provision/y000000000034.cfg for Yealink T21P
- http://192.168.10.220/provision/y000000000028.cfg for Yealink T28P
- and so on

<details>
<summary>This is an example of working template</summary>

    curl http://tempest-test.irontec.com/provision/y000000000052.cfg   

```
#!version:1.0.0.1
account.1.enable = 1
account.1.label = Line

auto_provision.mode = 6
auto_provision.schedule.periodic_minute = 1
auto_provision.server.url = https://tempest-test.irontec.com:1443/provision/t21E2
auto_provision.dhcp_option.enable = 0
auto_provision.pnp_enable = 0

local_time.time_zone = +1
local_time.ntp_server1 = es.pool.ntp.org
local_time.ntp_server2 =
local_time.interval = 1000
local_time.summer_time = 2
local_time.start_time = 1/1/0
local_time.end_time = 12/31/23

security.trust_certificates = 0
```
</details>


Not sure what's your terminal model, but that http request is public, can be validated by your browser and should work. That provisioned configuration contains the https specific provisioning for following requests, that will use terminal mac as parameter.


**Be sure you've configured templates for that model in your platform portal**, you can use the restore template button available for each template (generic and specific).

This is more an environment issue than a product bug, so please use the [ivozprovider-users group](https://groups.google.com/g/ivozprovider-users) for future reports.

Thanks a lot!!
