### ISSUE TITLE
Retail DDI fallback voicemail/number

### ISSUE THREAD

**Issue by Guigui37** [irontec/ivozprovider#284]
Should be nice to have a fallback option to retail DDIs. If the destination server is not up, it could say "number is unavailable, please leave a message" and send it to the mail associated to the DDI, or redirect it to a fallback number.

**Comment by Kaian** [comment]
Right now Retail Clients only receive external calls, and they only place externals calls. They don't have any service, nor Voicemails. Most probably the future of retail clients will be to simplify them instead of adding more features.

This kind of post-processing logics are implemented in PBX for users, using the "User not registered" call forward setting.

Regards!
