### ISSUE TITLE
Switch to disable for maintenance some kamailio proxies

### ISSUE THREAD

**Issue by Guigui37** [irontec/ivozprovider#291]
With distributed install, we could have more than one proxytrunk and one proxuser.
In the best world, everybody is using NAPTR/SRV, but that's not the case :( so sometimes, providers have a list of our proxytrunks, and is testing availability of each via SIP OPTIONS pings.
To properly offload a proxy, we should ask it to stop answering SIP OPTIONS, maybe with some kind of thing like this:
if (is_method("OPTIONS") && var(answer_options) == 'true') {send_reply(...)} else { exit; }
and control var(answer_options) with rpc so that its value can change when needed

**Comment by cruzccl** [comment]
Hi @Guigui37 

You are right, making load balancing and failover between several KamTrunks would be easier if carriers used NAPTR/SRV records but, as you say, they normally prefer plain IP addresses :disappointed: 

Having several KamTrunks running will lead to other unsolved problems though: these Kamailios should share some information between them, to control maximum allowed calls, etc. This is possible with Kamailio, but is not implemented in IvozProvider as a unique KamTrunks instance is assumed.

We usually use multiple machines running a cluster balancing this instance of Kamailio and its IP address in order to achieve high availability, but if you prefer running multiple instances you can make the answer to OPTIONS requests from carriers conditional with a variable as you propose.

We would be very grateful if you send us a PR with this change, if it is as simple as having a  RPC-controlled variable (that defaults to 'true' on Kamailio startup) we will be pleased to merge it :)

Regards,

**Comment by Guigui37** [comment]
Does it means that even with a NAPTR/SRV carrier, we still need a kamailio cluster to solve this SPOF ?
Is it the same with users ? I mean for now, we can't run more than one instance of kamusers ?

**Comment by cruzccl** [comment]
You are right, only one instance of each Kamailio profile is assumed and you need a cluster if you want to solve the SPOF.

To implement multiple KamUsers some analysis should be done:

- When Asterisk calls a user, which KamUsers would it use? Currently outboundproxy is set to users.ivozprovider.local but if there are more than one... You could make this domain point to different IPs addreses (one per KamUsers) to load balance between them, but them all of them should have access to users' registry information (despite which of them handled the register).

- Users maxcalls is handled by KamUsers, so all concurrent calls of a user must be handled by the same KamUsers (or share the current value between KamUsers).

- More unseen/unthough stuff.

To implement multiple KamTrunks some analysis is needed too:

- When Asterisk will use one or another? Currently there is a unique endpoint called proxytrunks and using trunks.ivozprovider.local. DNS load-balancing could be made but, does Asterisk cache the IP address for some time?

- More unseen/ungthough stuff.

We discarded this path and chose an easier way: configure a cluster that ensures that a unique instance of KamTrunks/KamUsers is running in any of the different machines located in different datacenters (manages both process and virtual IP address).

Regards,

**Comment by Guigui37** [comment]
Thank you for clarification about that.
If I understand correctly, it means that even with multiple kamtrunks and multiple kamusers, only one will work at a time, like an active/passive cluster.
This means that we can't offload properly an instance, without loosing calls that is manages ?
About user maxcalls, ok for this, I think if using a NAPTR record, when he is connected to a kamusers, he won't switch to an other. But about company maxcalls ? Is it the same behavior, meaning that each user in the company must be connected to the same kamusers ?
Thank you, discussion about that is important to see if we could solve this SPOF the best possible way.

**Comment by cruzccl** [comment]
Hi @Guigui37 ,

There are multiple solutions to all the problems that arise with that approach, that's why we chose the other way: geodistributed active/passive cluster.

As I explained above maxcalls and counters are not the hardest ones: SIP infraestructure becomes much more complex (think about application servers choosing kamailio instance).

We took the easiest approach to avoid this unnecessary (at least for now) complexity.

Regards,
