### ISSUE TITLE
Call handling for remote media w/ dynamic IP?

### ISSUE THREAD

**Issue by syadnom** [irontec/ivozprovider#299]
Is it possible to have a remote rtpengine on dynamic IP address *or* configured with a dynamic dns address?  I'm running into issues with the price of static IP addresses skyrocketing, now $25 extra in my area.  That money is much better spent on an upgraded speed plan than on a static IP that is otherwise unneeded.

**Comment by Kaian** [comment]
Hi @syadnom 

I have done a very fast check and seems you can specify a domain both in Media Relay sections of Ivozprovider (p.e. I have changed 127.0.0.1 with localhost) and the configuration of `/etc/default/rtpproxy`.

Take into account that most probably rtpproxy will not work without restarting if ip changes, but I'm not sure because we have never tested this kind of environments with dynamic IPs. We use static public IP addresses for MediaRelay and Proxies SIP Servers because most Peering services only accept RTP/SIP traffic from previously validated addresses.

Regards!

**Comment by syadnom** [comment]
thanks.
