### ISSUE TITLE
Add external number to huntgroup/user

### ISSUE THREAD

**Issue by MagnusVMI** [irontec/ivozprovider#353]
Hi,

I dont know if this feature already exists, but I cant find it.
We need to add external number to huntgroups, or the possible to add external number to a user that will be called simultant with the users device.

Example: 
User Bob, has extension 100. He has a Yealink phone on his desk, but he also want his mobile phone to call when someone calls his number (that is, both the Yealink phone and his mobile should be ringing).

Is this feature exist, or how could we do it?

// Magnus

**Comment by cruzccl** [comment]
Hi @MagnusVMI ,

IvozProvider makes an important distinction between internal parties (currently users, friends and retail accounts) and external parties (calls from/to carriers).

IvozProvider does not have control under things that happen when a call is made to an external party (e.g. calls that end in a cell phone's voicemail, progress messages when out of range, etc.). That's why external parties are only allowed as final-logics in all the flows defined for extensions/DDIs/whatever.

This means that once a call is placed to an external party, no more logic can be added afterwards:

- Call to a user that forwards to an external number: nothing else can be added.

- Incoming external call to a DDI that points to an IVR and the caller dials something considered as error, error behaviour points to an external number: nothing else can be added.

- Huntgroup define a call flow and a configuration to follow if no member answers the call. You can add an external number to this no-answer configuration, but not as a member (as it wouldn't be a final logic).

To sum up, **external numbers are only allowed as logic finishers and cannot be included in middle-logics**.

I guess you have also tried to add a user with an unconditional call forward to an external number to a huntgroup. This wouldn't work either, as **call-forwards are ignored in huntgroup calls**. The reason behind this behaviour is that when a call is delivered to a huntgroup, is not delivered to any particular member of the huntgroup, but to any of them: if a user is forwarded, try with the next one.

Finally, about **simultaneous calls in multiple devices: this is supported for SIP devices** (known as _parallel forking_, multiple registrations with same credentials in multiple devices), but not for a mixture like the one you describe (emulating some kind of IP/GSM convergency). The reason is the same one: the external call won't be a logic finisher. We think that's not a good idea and it would be better to have a softphone installed in the smartphone, registered with the same credentials as his Yealink: when Bob receives a call, both the yealink and the softphone will ring.

Sorry for the length of the response, but these features are often wanted and we think it is important to share the reasons behind not supporting them.

Regards,
