### ISSUE TITLE
NAT detection fails in LAN installations

### ISSUE THREAD

**Issue by rondaninigabr** [irontec/ivozprovider#4]
Cuando se instala en un entorno de privado (dentro de una LAN).
No se tiene audio en ninguna direccion

**Comment by cruzccl** [comment]
Buenas @rondaninigabr ,

El problema es la lógica de detección de terminales tras NAT que realiza el Kamailio de usuario llamando a **nat_uac_test(8)**.

En entornos puramente locales, esta detección concluye NAT cuando no lo hay, por lo que igual sería más adecuado utilizar **nat_uac_test(18)** en todas las llamadas del [archivo de configuración del Kamailio de usuarios](https://github.com/irontec/ivozprovider/blob/oasis/kamailio/users/config/kamailio.cfg).

Vamos a hacer pruebas para validar este cambio, puedes realizarlas tú mismo también si quieres sin más que cambiar todas las llamadas a esta función (excepto las que utilizan 64 para detectar WS) y reiniciar el servicio con:

```systemctl restart kamailio@users```

Muchas gracias!

-------------------------

Hi @rondaninigabr ,

The problem here is the NAT detection algorithm used to detect UACs behind NAT.

The current algorithm is **nat_uac_test(8)**:

```8 - The SDP is searched for occurrence of RFC1918 or RFC6598 addresses```

Maybe we should use **nat_uac_test(18)** instead:

```
16 - Test if the source port is different from the port in the “Via” header
2 - the "received" test is used: address in the “Via” header is compared against source IP address of signaling
```

We are going to test changing this setting in all nat_uac_test() calls in [Kamailio Users config](https://github.com/irontec/ivozprovider/blob/oasis/kamailio/users/config/kamailio.cfg) (except the ones using 64 to detect WS).

If you want to test it too, you can modify this file and restart this service with:

```systemctl restart kamailio@users```


Thank you!
