### ISSUE TITLE
Regexp for pricing patterns

### ISSUE THREAD

**Issue by Guigui37** [irontec/ivozprovider#469]
I see regexp working for routing patterns, but not for pricing patterns.
This could be a problem, for example in France, we have short number (2, 3, 4 or 6 digits), and usual long numbers (10 digits).
331XXXXXXXX is a long geographic number (like 332 333 334 335, or 339 for non geographic)
331015 is a short number, like 33118218.
If we have not yet (for any reason) registered the cost of 33118218 in pricing patterns and plan, it will goes through 331, with a really less expensive cost, and there, we will lost money.
With a regexp, the usual 10 digits numbers would be completely match (8 digits after the 331/332/333/334/335).

Could regexp logic be applied to pricing patterns like for routing patterns ?

**Comment by Kaian** [comment]
Hi @Guigui37 !

We are not planning any new feature or big change for oasis release from now as we are focusing on the next release. 

Not sure if [CGRates](https://github.com/cgrates/cgrates), the new tariffication engine, supports this feature (see issue 76 in their project). 

In case you are interested in implement it yourself, I will start with the [PricingPlans](https://github.com/irontec/ivozprovider/blob/oasis/library/IvozProvider/Model/PricingPlans.php) model, where the price selection is done. You also have the possibility to mark the peering contracts with externally rater flag and create a script to update the price field in mysql directly.

Regards!

**Comment by cruzccl** [comment]
Hi @Guigui37 ,

My 2 cents about this:

- Initially, there was a unique table with all routing/pricing patterns: TargetPatterns.

- We noticed that it was quite unusable to have the same patterns for both processes: pricing patterns are thousands prefixes given by carriers while routing is usually made by country prefix.

- At this point, RoutingPatterns was created (with the same structure) for routing and TargetPatterns was left for Pricing Patterns (the table was not renamed though).

- Regexp field in RoutingPatterns is actually a regexp as routing process has metrics to solve the case of colliding regexps (destinations included in more than one regexp): it will be routed using the OutgoingRouting with lower metric. A call must be routed using a OutgoingRouting rule and it does not matter with pattern within that rule has matched.

- Regexp field in TargetPatterns was converted into a prefix-only field, as opposed to routing process, a call MUST match a unique pattern in TargetPatterns (in order to set the price for the call). Metrics in PricingPlans solve the problem between PricingPlans but **there is not a metric field to solve a collission between 2 patterns in the same PricingPlan**.

This last situation could have been solved adding a metric to patterns within a Pricing Plan, but we discarded this approach in order to keep things simpler: just take the longer prefix that matches inside a PricingPlan as there will be no possible collision.



As @Kaian says, all this is only valid for Oasis, as in Artemis all things related to billing have totally changed with the inclusion of CGRateS.


Regards,
