### ISSUE TITLE
Call forwarding caller id Isue

### ISSUE THREAD

**Issue by lainard** [irontec/ivozprovider#493]
Hello,

I set up call forwarding rule per users to my mobile phone, and simulate the call forwarding.

I set Outgoing DDI Rule to: Keep Original DDI

Wierd thing is the caller id i received on my mobile phone is +34 6906XXXXX (SPAIN)

I set the company to Belgium and my Company caller id is +32 XX XX XX XX

anyone having this smiliar issue?

**Comment by Kaian** [comment]
Hi @lainard 

I have edited the note to remove some of the numbers because it seems a personal mobile. I don't know that number and [a quick search in the code](https://github.com/irontec/ivozprovider/search?utf8=%E2%9C%93&q=690673990&type=) doesn't show it's pressent in the code.

I would start checking the outgoing INVITE to your carrier (sngrep may help you with that) and/or asterisk logs to see where the problem could be.

Thanks!

**Comment by lainard** [comment]
It seem issue has been solved,

it seem i cant use the E.164 directly out of the box, 

i need to create number transformation manually and all solved.

**Comment by Kaian** [comment]
Good to know we didn't leave one mobile number in the code!

Closing then :+1:
