### ISSUE TITLE
Brand Portal - unable to change password, or add new Brand Admins

### ISSUE THREAD

**Issue by flantel** [irontec/ivozprovider#514]
Hi

Part bug report, part feature request.

Using Bleeding installed via apt.

## Bug
It appears that the only place where it is possible to add/edit a Brand Admin is in the God portal. When a Brand Admin logs in there is no way to change their password. There should be.

## Feature Request.
I should also be possible for the Brand Admin to create new Brand Admins - ideally also to be able to restrict these additional admins to certain functions/menu items - for example only Billing, or Routing, or Companies.

**Comment by Kaian** [comment]
Hi @flantel 

> It appears that the only place where it is possible to add/edit a Brand Admin is in the God portal. When a Brand Admin logs in there is no way to change their password. There should be.

This is an enhancement. The same applies for some information of Companies that can not be edited from Company portal, or Brand Information that can not be edited from Brand portal.

We will like to make this information accessible from the other portals in the future (like the profile settings with password or display name of logged user), but this can not be implemented with current portals framework (klear).

> I should also be possible for the Brand Admin to create new Brand Admins - ideally also to be able to restrict these additional admins to certain functions/menu items - for example only Billing, or Routing, or Companies.

I see two enhancements here:

1. Creating Brand Administrators from Brand Portal. 
 Not sure the rest of the team opinion, but I prefer to keep it as it is right now. Global admins create and control their Brand administrators (how many are and what can they see), while brands do the same with their company users. Brand administrators are responsible of very sensitive information and Global admin must ensure that knows every of them.

2. Allow configuration of what sections can see each administrator
We've been thinking about this since long time ago, configuring permissions to read/write sections per user, but this must be implemented in the API before, so this won't happen in current portal framework. I will like to see this in the future versions, but this is still far in the roadmap.

Thanks a lot for the feedback!!
