### ISSUE TITLE
anti-flooding mechanism question

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#542]
Are peers IPs, the ones we are going to get a lot of traffic from, not excluded from antiflood by default?

Reading the docs (https://irontec.github.io/ivozprovider/en/platform/antiflood.html) I understand they are not.

Should we add the IPs of peers to antiflood trusted IPs list? And should we do it for SIP traffic IPs and RTP traffic IPs?

It would be great if this could be clarified on antiflood docs section.

**Comment by cruzccl** [comment]
Hi @manfer,

You are right, all excluded elements are specified in that [the documentation section](https://irontec.github.io/ivozprovider/en/platform/antiflood.html).

You can also see [here (for users)](https://github.com/irontec/ivozprovider/blob/a55c689e391e8cb78737bcf3346e5e0084517179/kamailio/users/config/kamailio.cfg#L1346) and [here (for trunks)](https://github.com/irontec/ivozprovider/blob/a55c689e391e8cb78737bcf3346e5e0084517179/kamailio/trunks/config/kamailio.cfg#L1055) the underlying logic of antiflood mechanism.



Antiflood **only filters SIP traffic** and elements not listed there, won't be excluded. The documentation may be improved to warn that **PeeringContracts with high traffic rates should be added to Antifllod Trusted IPs**. The reason behind this is that PeerServers can be defined with DNS entries instead of static IPs. Converting those DNS entries to IPs would requiere and additional timer task to keep them updated, etc.

Regards,

**Comment by manfer** [comment]
That's what I thought just SIP IPs.

I was not sure if we should add them to the trusted IPs. Thanks for clarification.

**Comment by Kaian** [comment]
Closing this, feel free to comment if the you need more info!

Regards!
