### ISSUE TITLE
Music on Hold instead of Ringing on Ring Groups

### ISSUE THREAD

**Issue by amvidalrc** [irontec/ivozprovider#562]
Hello. Maybe I'm crazy but I can't find any way to put Moh instead of ringing when calling to Ring Groups. I'm using 1.7.

¿It's possible to do that?

Thanks in advance!!

**Comment by Kaian** [comment]
Hi @amvidalrc 

I think this is a duplicate from #184. Also check #283.

To sum up, there is no setting to select the ring mode, although you could change asterisk dialplan for huntgroups. In order to avoid the problems mentioned in the other issues I think we require Local channels to dial huntgroups, so there's much more change that just a Dial application flag.

Regards!!

**Comment by amvidalrc** [comment]
Thanks for the Info!! I will test.

**Comment by Kaian** [comment]
Closing this as duplicated. 

Feel free to reopen or comment if you have more info or want to provide feedback of your tests.

Regards!
