### ISSUE TITLE
Voicemail MWI

### ISSUE THREAD

**Issue by pacomms** [irontec/ivozprovider#569]
Hi, i have installed a single node for testing, i ahve managed to get a phone connected and works ok however i have noticed the message light doesnt come on when a vm is left ? Is this a known bug ?

**Comment by manfer** [comment]
Yes it is https://github.com/irontec/ivozprovider/issues/536

In that thread you have see links to the opened issues about MWI

**Comment by pacomms** [comment]
Thats a real shame then, having no MWI for voicemail makes this platform a no go for us to use for our cloud offering, i know the developers are working on other things but it seems amazing to me that they would not fix core pbx issues before wish list items .. will keep an eye on it and maybe look again when this has been fixed.

**Comment by Kaian** [comment]
Hi @pacomms 

The platform actually has Unsolicited MWI implemented, but you must reload asterisk module as #367 mentions in order to take into account **new** created terminals. This is due to an asterisk bug in res_pjsip_mwi, and ugrading to latest LTS versión may fix the problem. 

We are working on the routing and billing modules a lot because this project is expected to be a provider solution, so pbx will probably lose weight release after release and things will be more balanced in terms of features. Of course, we always try to adapt the solution for our clients, priorizing their needs and fixing the problems they detect as important. After all, this project is possible thanks to them. 

If reloading asterisk module periodically (or after a new terminal is created) is not possible for you, consider contacting our comercial team to priorize this problem over the others, otherwise it'll hardly be fixed unless we have spare time, someone contributes a fix or one of our clients is affected.

I just wanted to clarify how issues are prorized in each release (most probably we should create a FAQ with this information). Feel free to request any extra information!!


Regards!

**Comment by Kaian** [comment]
Closing this as duplicated then.

Feel free to add any comment or request further info!
