### ISSUE TITLE
artemis: 2.X allowing more than one codec in Terminal configuration

### ISSUE THREAD

**Issue by dsmaldone** [irontec/ivozprovider#573]
I would ask you to consider giving the possibility to select more than one codec in "_Company Configuration->Terminals_" under the option "Allowed audio codecs:"
Currently, because of the dropdown list selector, is it possible to select just one codec at time.

**Comment by cruzccl** [comment]
Hi @dsmaldone, 

This limitation was added for terminals in 44f0efa due to Asterisk SDP negotiation problems. It is not a UI problem, this restriction was added intentionally to avoid several no/one-way audio problems.

In Artemis, transcoding in media-relay added in #387 allows Wholesale and Retail clients to choose more than one codec, as long as Asterisk is not in the media or signalling path of their calls. For calls traversing Asterisk (vPBX and Residential clients), this limitation should be mantained until new versions of Asterisk solve this problem.

Regards,
