### ISSUE TITLE
delete demo brand

### ISSUE THREAD

**Issue by miquelinv** [irontec/ivozprovider#581]
Hello

In the manual I have not seen that the demo brand can not be deleted, nor have I seen what we should do if we do not want to have it.

I mention it because we have deleted the demo brand, and we have stopped accessing the platform, we have restored a copy of mysql and it has been fixed, but if it is possible that it stops working by deleting the demo brand, this should be eliminated. option with the demo brand.

**Comment by Kaian** [comment]
Hi @miquelinv 

The problem is actually more related to Brand's URLs rather than the Brand itself.

When you enter the administration portal, it tries to find the matching configuration in BrandURLs table and apply the theme, title and so on. If none is found, it simply searches for an URL with type _god_ and apply its configuration. Most probably Demo Brand was the only brand with a BrandURL of type _god_, so deleting it breaks this behaviour.

This is actually a long time known bug and we will try to fix this fallback behaviour so, in case no URL matches, the god portal will be shown with a default title _Administration portal_ and _Redmon_ as theme.

Thanks for reporting!
