### ISSUE TITLE
Question: multi proxy

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#649]
On the scale graph of the readme, on the left it shows and image that recalls a standalone system (or a distributed system with just one instance of each service). On the middle shows an image that can be seen as an installation with two proxies (trunks and users) an multiple application servers. And on the right image an image that shows multiple proxies two.

But I always read here that the system is ment to use only two proxies so I can't imaging how the implementation of the right image could be done.

I have tried myself two solutions to try to handle proxy failover.

On a first solution I use two totally independent installations of ivozprovider, one to work as primary and the other as secondary. On voip devices I configure one line registered to the primary ivozprovider (for example client1.sip.ivozprovider1.test for this primary user proxy) and a second line registered with the secondary ivozprovider (for example client1.sip.ivozprovider2.test for this secondary user proxy).

PROS
- Very simple to understand and implement

CONS
- When something is added or reconfigured has to be done in both installs. Error-prone.
- CDRs are spread on two systems

These CONS could be solved by coding some software which makes use of an API to talk to both ivozprovider instances to automate configs and get CDRs.

On a second solution I make use again of two ivozprovider installations but they are not independent. Their Data Service are configured with a master-master replication (excluding just ProxyTrunks and ProxyUsers tables). I make use of SRV records for registration (for example client1.sip.ivozprovider.test for both user proxies) so while primary ivozprovider is running registrations goes to that instance and only if that ivozprovider instance fails then registrations goes to second instance.

PROS
- Things only need to be configured once
- No need to get CDRs from two places.

CONS
- Lack of simplicity.
- Posible unexpected errors arise that I don't take into account. Maybe there are more database tables that should be excluded of master-master replication. The scripts that generate CDRs should probably be run only in one of the instances (oasis).

I have no confidence on this second solution to try it on production.

For sure there are better implementations that I'm not trying. The hardest to understand for me is to make several proxies read/write to same data service without problems. Being the most worrying problem two proxies trying to write data at same time.

Am I complicating things too much? Any advice?

**Comment by powerpbx** [comment]
I am presently thinking about the same things.  Ideally, at least two physically separate geo redundant installs with the databases connected master-master.

I think the key question is how to do that and still have failover or load balancing between the two installs.  I can think of at least two ways to do it.  You can use an AnyCast IP so that both installs have the same IP/domain etc.  Which proxy your SIP device uses will depend on your physical location.  Load balancing should just work with AnyCast but failover is a little tricky.  There would need to be some monitoring and extra software to do it right.

The other possible solution is to use different IP's and a DNS provider with a failover feature.  So everything uses DNS and if one IP stops working the DNS provider switches over within a few minutes.  However, DNS is cached at various locations down the line so it could take some time for the changes to propagate.

Ivoz suggested using a floating IP but that is usually only possible if everything is in the same datacenter.  So you are not datacenter redundant.  I know AWS has elastic IP's that are datacenter redundant in the same region.  So you could just have the proxies behind that and put everything else somewhere else.  The problem with AWS Elastic IP's is that they use NAT. SIP + NAT makes things more complicated.

**Comment by cruzccl** [comment]
Hi,

We close this issue as we currently think that adding proxies would increase overall complexity and we prefer multiple proxies managed by a cluster that ensures that a unique proxy is available.

This is of course is a subjective opinion and may change in the future, but we have no near intention to implement it.

Thank you very much for your thoughts, though.

Regards,

**Comment by powerpbx** [comment]
> we prefer multiple proxies managed by a cluster that ensures that a unique proxy is available.

How would that be done on Artemis?   We cannot use floating IP and pacemaker because we need datacenter redundancy.  So least 2 IP addresses corresponding to 2 proxy servers.    We do not need load balancing on the proxy.  So just a primary/secondary setup.  If the phone cannot reach proxy 1 it goes to proxy 2.  We have something like that running now using stock artemis.  Yealink has a primary/secondary outbound proxy server setting so that is where the 2 IP's go.  The SIP domain is used on server host setting and does not to be resolvable.  So it could be something.local

For phones without primary/secondary outbound proxy setting there is DNS SRV.  You can use a DNS provider with a failover feature.  That is not ideal because of DNS caching and propagation but it better than nothing.

**Comment by powerpbx** [comment]
> Hi,
> 
> We close this issue as we currently think that adding proxies would increase overall complexity
> Thank you very much for your thoughts, though.
> 
> Regards,

It doesn't have to be complicated.  It could be as simple manually selecting what proxy you use in the GUI.  User agents do not need to talk between proxies/clusters.  It could be one or the other and you could have several selections based on geography.  If you are not familiar with voip.ms you can get a trial account and see how they do it.  The main limitation is that all user agents need to be on the same proxy/cluster to talk to each other.
