### ISSUE TITLE
Question, which version should I be using?

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#664]
If we are looking to implement a clustered solution in the near future, which version should we be using?  Oasis, Artemis, or bleeding?  We don't want to have to deal with a painful upgrade in the future. It sounds like Oasis is quite a bit different than Artemis because of the different billing engines.  So we want to be using whatever will be production and continuously developed/tested/maintained long term, starting maybe 6 months from now.

How far is artemis from becoming production?  Is bleeding just a continuation of artemis?

**Comment by powerpbx** [comment]
Yes, that is what the readme says.  My question is when will Artemis be ready and is that the branch we should be testing on as we prepare to use in production?

**Comment by Kaian** [comment]
Hi @powerpbx 

If you're looking at the future, Artemis is the way to go. As @manfer mentions, oasis will no longer receive any new feature (unless totally required). 

There is no deadline yet for artemis. It's marked as testing because our production environments in that release are not tested enough and we found small bugs here and there everyday. Of course, you can use it and test it. We appreciate feedback and bug reports, although we can only fix software faults. Any other kind of support has to be requested to comercial@irontec.com 

Bleeding is the development branch and should not be used under no circustance for production environments. If we have to hotfix a security bug we'll do it in artemis branch directly.

Regards!
