### ISSUE TITLE
billing: prepaid is charging twice/double

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#703]
I'm testing bleeding prepaid feature and I found a bug.

When a prepaid client reaches his limit during a call the call is hang up by the system and instead of substract the cost of the call from his balance so it finishes with a value of 0, after the call his balance becomes -balance.

Just to explain it more clearly.

- A client's current balance is 100€.
- He calls a number xxxxxxxxx which cost is 1€ per second.
- When the call reaches 100 seconds it is hangup by the system because he has consumed his balance. 
- His balance should become 0€ but it becomes -100€.

**Comment by manfer** [comment]
Looks like it is in fact on every call. It is charging twice. During call the balance is updated and after call again.

**Comment by cruzccl** [comment]
254ce6b8c9e5deae26e7ed6a4d2be28987aaaa70 broke this :(

This change was introduced to make prepaid call rerating possible (ignoring sm_costs entries), otherwise price changes won't apply to already billed prepaid calls.

Removing this line and restarting cgrates should fix this issue, but breaks prepaid call rerating.

We are working on the solution, thank you for the report!

Regards,
