### ISSUE TITLE
pike: List and allow blocked IPs

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#704]
I have faced this problem several times. It happens on clients with a vpbx that has several devices, don't know exactly how many are needed for the problem to happen. When his internet connection drops for some time and it comes back some minutes later, his devices start sending register and subscribe request and they are blocked by the antiflood mechanism.

When the client is on a static IP it can be added as an antiflood trusted IP (and probably in the filter by IP in the vpbx configuration) but if the client has a dynamic IP that solution is not possible.

Where is the antiflood mechanism? Is it in kamailio? How can we remove an IP from antiflood on linux console?

I suppose there is no solution for this. The mechanism is good for security. Can you point me to the antiflood mechanism configuration parameters just to take a look?

**Comment by cruzccl** [comment]
Hi @manfer,

As you say, it is a known situation. In those scenarios with lots of phones behind the same public IP address, this address should be a static IP so that it can be excluded from antiflood.

You can see how Kamailio's [pike module](http://kamailio.org/docs/modules/5.1.x/modules/pike.html) is configured here:

https://github.com/irontec/ivozprovider/blob/6a77222dd8144d41b0fd40592f9279263f96e41b/kamailio/users/config/kamailio.cfg#L323 and https://github.com/irontec/ivozprovider/blob/6a77222dd8144d41b0fd40592f9279263f96e41b/kamailio/trunks/config/kamailio.cfg#L238

Regards,

**Comment by manfer** [comment]
Thanks @cruzccl ,

I'm investigating how to deal with pike. I will try to force an IP blocked by pike and try to find a way to allow it.

Just in case is useful to someone. To list pike status from CLI.

`kamcmd-proxyusers pike.top`

**Comment by cruzccl** [comment]
Hi @manfer,

We may implement in the future as a new feature:

- Add blocked IPs to a new table.
- New God section showing this table's entries: IP addresses that have been blocked at least once.
- Allow adding easily to authorized IPs table.

Regards,

**Comment by Kaian** [comment]
Blocked IPs web section was implemented in #1326 so I'm closing this.
