### ISSUE TITLE
Artemis, more relaxed password rules

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#789]
Requiring 3 Upper, 3 Lower, 3 digits, and a * , +, _, - " for a terminal password may seem a bit excessive to some people.  If entering from a phone keypad it can make it more difficult.  Is there any way to relax this default or make it configurable?

If not please label this as a  feature request/product change request

**Comment by Kaian** [comment]
I agree the symbols may be a bit excessive, but having long enough secure password (min 8-10 chars with at least one down,up and number and allowing but not enforcing symbols) is critical for provider solutions, because in most scenarios, data is still sent to the server in plain UDP with MD5 authorization algorithm. It would be another story if everyone would use TLS 0:-)

 We usually set passwords from terminals web interfaces and/or using terminal provisioning, so it's a pain that only happens once.

I leave the issue here for future reference and in case we evaluate chaning the existing rules.

Thanks for the feedback!

**Comment by powerpbx** [comment]
Just want to point out that rules like these are no longer considered best practices.  The guy who originally invented the guidelines says it was a mistake.

https://www.businessinsider.com/guy-who-made-passwords-a-pain-says-he-was-wrong-2017-8

So the new recommendation appears to be to combine words that are easy to remember.  Less emphasis on hard to remember combinations of special characters and numbers.  At the very least, I don't think it is necessary to require at least 3x3 of anything.

**Comment by cruzccl** [comment]
Hi @powerpbx,

We force passwords to be that strong to avoid brute-force-attacks as IvozProvider is thought to be exposed to the wild Internet. Currently, there is no intention/need to make them weaker.

If you need to make this configurable and you are interested in sponsoring such feature, please contact comercial@irontec.com.

Regards,
