### ISSUE TITLE
Add sentinel support from cgrates upstream

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#828]
Cgrates upstream now supports redis sentinel.

https://github.com/cgrates/cgrates/commit/25e3cda1d71e04cf35e0adab8b6ac324b3faf314

https://github.com/cgrates/cgrates/commit/83f21c17fe6138c32accba34e4cbad271ec98cbf

https://github.com/cgrates/cgrates/commit/34a5843beafc7b563f6090bad2a689f0a7fa5c3e

**Comment by powerpbx** [comment]
What is the status of this?  Do you have any plans to rebase to current cgrates stable since there appear to have been a lot of changes since you forked it.

**Comment by Kaian** [comment]
Hi @powerpbx 

Sentinel seems quite interesting and the way to go for proper redis high availability. We currently use pacemaker ms resource with data local address.
Sadly, picking those commits will require some time because they don't apply directly to our current fork.

Like for other softwares used in Ivozprovider (asterisk, kamailio, rtpengine,..) we choose a version and test it, adding required patches (sometimes from upstream) to make it as stable as possible. We stick to that version until we require a functionality from a newer version. Then the whole process of testing and patchings is repeated.

For CGRateS, as they don't follow a numeric versioning anymore, we've choosen a commit and won't be moving from there anytime soon. If you want us to schedule more resources to this, don't hesitate to conctact our sales departament at comercial@irontec.com. You can also submit a pull request with the feature and we will try to test it whenever we have some spare time. 

Otherwise this will be marked as future. 

Thanks

**Comment by Kaian** [comment]
I will try to priorize this for next  releases. Any thoughts about your patched version with sentinel?

Did you stress tested the new version or tested with high amount of records?


Thanks for the info @powerpbx!

**Comment by powerpbx** [comment]
We have not done stress testing of anything yet.  We are waiting for artemis to be production ready before we do that.

**Comment by Kaian** [comment]
Included in 2.9.2

Thanks for all @powerpbx
