### ISSUE TITLE
Workflow question regarding branching vs patching of a fork of ivozprovider

### ISSUE THREAD

**Issue by powerpbx** [irontec/ivozprovider#875]
This is a general question regarding workflow.  You maintain your own forks of cgrates as well as other projects.  You appear to be using quilt and applying patches instead of just using git branching and commits.  In those cases, you are creating debian specific branches first and then applying your patches inside the debian specific branch.

Does using quilt patching also make sense if we were to maintain our own parallel fork of ivozprovider, which is already debian specific?  The only changes we would be doing would be commits inside our own feature branch, separate from upstream bleeding and upstream artemis.

We would continue to do it the same way as you do it with a fork of your patched fork of cgrates and the other forks, using quilt.  So this question is specific to your ivozprovider project, which is not a fork.

**Comment by Kaian** [comment]
Hi @powerpbx 

Both packaging patching and forking/branching are good approaches to maintaining changes in the free projects we use in ivozprovider. We have chosen the first one, because that way all the changes from the original software are stored in a single directory.

We will like to move with the other free software projects that makes ivozprovider possible, after testing the changes on newer versions and check they fulfill the needs of the project, so we avoid creating a branches with custom commits that we change over the time. Instead, the debian/patches directories contain the latest version of each patch (sometimes modified in multiples commits), and when we want to test a new software release, we just copy that directory and adapt those patches to apply to the new code state. Some of these patches are taken from upstream, so regression commits in this case are just as simple as removing the patch (because it's already applied).

As said, both approaches are good, you can cherry-pick for upstream to your forked branch and rebase commits (fixing the conflicts) when you want to change your version, or just merge and check what patches are still required and what must be updated to fix conflicts.

Regards!
