### ISSUE TITLE
Handle uploaded files through API

### ISSUE THREAD

**Issue by glacroix** [irontec/ivozprovider#913]
Hello,

I'm trying to use the locutions API (POST clients/locutions) the upload a mp3 prompt file to the system. So far, I can only populate the DB (table locutions) but don't manage to see how to send the actual media file and how the conversion is done from Original to Encoded (and what/how this conversion is done - builtin the API logic ?).

I have been through the documentation but didn't find any solution so far. Can the APIs act the same way as the Web admin (just by dropping a sound file and let the things get done automatically) or something else needs to be done to do that ?

Thanks for your help !

Bye,
Guillaume

**Comment by mmadariaga** [comment]
Hi @glacroix,

Even though entity files are exposed on the API spec we don't have any handler implemented yet. https://github.com/irontec/ivozprovider/blob/570496a6333780970302330f9c7d8ce6ec129c5a/library/Ivoz/Api/Swagger/Metadata/Resource/ResourceMetadata/OperationMetadataFactory.php#L52 

That's something we plan to do during artemis development. Meanwhile, you could implement your own LucutionDto::denormalize method so that LucutionDto->setOriginalFilePath() is called. Everything else should be automatic (encoding, etc.).

Let us know if you have any further doubt

**Comment by glacroix** [comment]
Hi @mmadariaga ,

Thanks for the hint, I will try to dig in.

Could you just be more specific about the scenario there ? I can see that the files are stored in the storage directory, with a directory starting with the first digit of the ID in the table Locutions. Is that handled automatically ?

Besides, what mechanism makes the conversion ? Sorry for the newbie questions, just arrived there :)

Thanks !

**Comment by mmadariaga** [comment]
>Could you just be more specific about the scenario there?

Sure, It's quite complex, though. I'll assume that you've some php/symfony skills here :)

In order to avoid inconsistent entity states, we don't allow entities to be updated through their setters directly ([protected methods](https://github.com/irontec/ivozprovider/blob/bleeding/library/Ivoz/Provider/Domain/Model/Locution/LocutionAbstract.php#L271)), plus non nullable attributes are required in the [constructor](https://github.com/irontec/ivozprovider/blob/bleeding/library/Ivoz/Provider/Domain/Model/Locution/LocutionAbstract.php#L53).  State updates are almost always done using data transfer objects ([dto](https://github.com/irontec/ivozprovider/blob/bleeding/library/Ivoz/Provider/Domain/Model/Locution/LocutionDto.php)).

Because of that, **you'll need to set originalFilePath in LocationDto before anything else**. You can find an example of a custom denormalization [here](https://github.com/irontec/ivozprovider/blob/bleeding/library/Ivoz/Provider/Domain/Model/User/UserDto.php#L117). You can just set a harcoded path to a file at /tmp if you want for testing.

> I can see that the files are stored in the storage directory, with a directory starting with the first digit of the ID in the table Locutions. Is that handled automatically ?

**Yes**. No matter whether you're using the API or any admin portal, dto <-> entity sync process will start at [DoctrineEntityPersister](https://github.com/irontec/ivozprovider/blob/bleeding/library/Ivoz/Core/Infrastructure/Domain/Service/DoctrineEntityPersister.php) service  and, in the case of locutions, you'll end up at [LocutionAssembler](https://github.com/irontec/ivozprovider/blob/bleeding/library/Ivoz/Provider/Application/Service/Locution/LocutionAssembler.php) witch makes use of  [FileContainerEntityAssemblerTrait](https://github.com/irontec/ivozprovider/blob/bleeding/library/Ivoz/Core/Application/Service/Traits/FileContainerEntityAssemblerTrait.php). Check those services if you're curious about implementation details.

Right after the entity is updated, it will be marked for persist. Here, lifecycle services come into play:
[Filesystem/Commit](https://github.com/irontec/ivozprovider/blob/bleeding/library/Ivoz/Core/Infrastructure/Persistence/Filesystem/Commit.php#L10) moves the file from /tmp/whatever to storage path.

[Locution/SendRecodingOrder](https://github.com/irontec/ivozprovider/blob/bleeding/library/Ivoz/Provider/Domain/Service/Locution/SendRecodingOrder.php#L13) Registers an asynchronous gearman job that will encode original file. 

> what mechanism makes the conversion ?

The encoding process itself is located at: https://github.com/irontec/ivozprovider/blob/bleeding/microservices/workers/src/Worker/Multimedia.php

Hope it helps

**Comment by mmadariaga** [comment]
Already implemented https://github.com/irontec/ivozprovider/pull/1012
