### ISSUE TITLE
Route from IVR  to Queues

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#985]
From IVR is possible to route to : Extensions,Numbers, Voicemail, Nothing, Conditional Route,

It would be great to be able to route to queues

Provisionally I think I can do it with a conditional route and then queue

2.10~2.10.0~20190430.2009~1db7b82+artemis all

**Comment by Kaian** [comment]
Not all endpoints route to all options, but most of them route to extension that can be used as glue between different endpoints. Extensions route to almost everything in the platform, so I would recommend those instead of conditional routes.

We would like to rework how routes are stored and allow free routing selection (everything routing to everything), but that won't happen in Artemis release. If you still need that routing option, consider contacting comercial@irontec.com to sponsor this feature.

Thanks!!

**Comment by gil-obradors** [comment]
Ok, extension to route is enough.

Thanks to yours
